[pytest]
asyncio_mode = auto
filterwarnings =
    error
    ignore:notifyAll.*:DeprecationWarning
    ignore::ResourceWarning
    ignore::pytest.PytestUnraisableExceptionWarning
    ignore:pkg_resources is deprecated as an API.*:UserWarning
markers =
    asyncio: mark async tests managed by pytest-asyncio
